#!/usr/bin/env bash
#displays "bad luck", "good luck" and "best school" depending on iterated number

i=1
while (( i<=10 ))
do
	if (( i == 4 ))
	then
		echo "bad luck"
	elif (( i == 8 ))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$(( i+1 ))
done
