#!/usr/bin/env bash
#dispays text using while loop

i=1
while (( i <= 20 ))
do
	if (( i == 5 ))
	then
		echo "bad luck from China"
	elif (( i == 10 ))
	then
		echo "bad luck from Japan"
	elif (( i == 18 ))
	then
		echo "bad luck from Italy"
	else
		echo "$i"
	fi
	i=$(( i+1 ))
done
