#!/usr/bin/env bash
#configure a ufw to block all incoming traffic with exception of TCP ports 22, 443, 80

apt-get install ufw
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
ufw allow 22
ufw allow 443
ufw allow 80
